@Library('jenkinslib') _

nodePipeline{
  containerName = 'test-node-app'
  dockerRepo = ''
  registryCredentialsId = 'docker-credentials'
  gitRepo = 'https://github.com/ogomezstratio/test-NodeApp.git'
  gitCredentials = '	ogomezStratio'
}
